const URL_GAS = 'https://script.google.com/macros/s/AKfycbzTLDlivTgJS3QUIm-qmaHRFLVmu-aPYdYwMoG-YdG6xSyeUF9sDUaHV7_E-4xLUAiB/exec';
console.log('App.js loaded');

// POPUP - TAMBAHAN SAJA
function showSuccess(m){Swal.fire({icon:'success',title:m,showConfirmButton:false,timer:2000,background:document.documentElement.classList.contains('dark')?'#064e3b':'#ecfdf5'});}
function showError(m){Swal.fire({icon:'error',title:'Oops',text:m,confirmButtonColor:'#800000'});}
async function showConfirm(m){return (await Swal.fire({title:m,icon:'question',showCancelButton:true,confirmButtonText:'Ya',cancelButtonText:'Batal',confirmButtonColor:'#800000'})).isConfirmed;}
window.alert=showSuccess;

let deferredPrompt;const installPopup=document.getElementById('installPopup');const btnInstall=document.getElementById('btnInstall');
const isInStandaloneMode=()=>window.matchMedia('(display-mode: standalone)').matches||window.navigator.standalone;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;if(!isInStandaloneMode()){installPopup.classList.remove('hidden');installPopup.classList.add('flex');}});
btnInstall?.addEventListener('click',async()=>{deferredPrompt.prompt();await deferredPrompt.userChoice;installPopup.classList.add('hidden');deferredPrompt=null;});
if('serviceWorker'in navigator){navigator.serviceWorker.register('/sw.js');}

const app=document.getElementById('app');let user=JSON.parse(localStorage.getItem('user')||'null');let isDark=localStorage.getItem('dark')==='true';
let currentType='';let stream=null;let animationFrame=null;let currentLocation={lat:0,long:0,alamat:'Mencari GPS...'};
let currentPage='home';let statusServer={};let dataRekap=[];let dataPatroli=[];let dataKejadian=[];let dataPembinaan=[];
if(isDark)document.documentElement.classList.add('dark');

function render(){if(!user)return renderLogin();renderDashboard();}
function renderLogin(){app.innerHTML=`<div class="flex items-center justify-center min-h-screen bg-gradient-to-br from-red-800 to-red-900 p-4"><div class="bg-white dark:bg-gray-800 p-8 rounded-2xl w-full max-w-md"><h1 class="text-2xl font-bold text-red-800 text-center mb-6">Absensi Karyawan</h1><input id="username" placeholder="Username" class="w-full p-3 border rounded-lg mb-3 dark:bg-gray-700"><div class="relative mb-4"><input id="password" type="password" placeholder="Password" class="w-full p-3 border rounded-lg dark:bg-gray-700"><i id="eyeIcon" onclick="togglePass()" class="fa-solid fa-eye absolute right-3 top-4 cursor-pointer"></i></div><button onclick="login()" id="btnLogin" class="w-full bg-red-800 text-white p-3 rounded-lg font-bold">Masuk</button></div></div>`;}
async function login(){const u=document.getElementById('username').value.trim();const p=document.getElementById('password').value.trim();if(!u||!p)return showError('Isi username & password');const b=document.getElementById('btnLogin');b.disabled=true;const r=await api('login',{username:u,password:p});if(r.status==='success'){user=r;localStorage.setItem('user',JSON.stringify(user));render();}else{showError(r.message);b.disabled=false;}}
async function logout(){if(!(await showConfirm('Yakin logout?')))return;localStorage.removeItem('user');user=null;render();}
function togglePass(){const p=document.getElementById('password');p.type=p.type==='password'?'text':'password';}
function toggleDark(){isDark=!isDark;localStorage.setItem('dark',isDark);document.documentElement.classList.toggle('dark');}
function renderDashboard(){
  app.innerHTML=`
  <nav class="bg-red-800 text-white p-4 flex justify-between items-center sticky top-0 z-10">
    <div class="flex items-center gap-3"><i class="fa-solid fa-user-shield text-xl"></i><div><h1 class="font-bold">Hi, ${user.nama}</h1><p class="text-xs opacity-80">${new Date().toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long'})}</p></div></div>
    <div class="flex gap-2"><button onclick="toggleDark()"><i id="darkIcon" class="fa-solid ${isDark?'fa-sun':'fa-moon'}"></i></button><button onclick="openProfil()"><img id="avatarNav" src="${user.foto||'https://ui-avatars.com/api/?name='+encodeURIComponent(user.nama)+'&background=800000&color=fff'}" class="w-9 h-9 rounded-full border-2 border-white"></button></div>
  </nav>
  <div id="contentArea" class="p-4 max-w-2xl mx-auto pb-32">${renderPage()}</div>
  <div class="fixed bottom-0 left-0 right-0 bg-white dark:bg-gray-800 border-t shadow-lg">
    <div class="grid grid-cols-5 max-w-2xl mx-auto">
      <button onclick="switchPage('home')" class="py-2 flex flex-col items-center ${currentPage==='home'?'text-red-800':'text-gray-500'}"><i class="fa-solid fa-house text-xl mb-1"></i><span class="text-xs">Home</span></button>
      <button onclick="switchPage('rekap')" class="py-2 flex flex-col items-center ${currentPage==='rekap'?'text-red-800':'text-gray-500'}"><img src="https://raw.githubusercontent.com/ekyarsakarya-eng/absensi-JSKN/main/icon-rekap.png" class="w-6 h-6 mb-1 ${currentPage==='rekap'?'':'opacity-50'}"><span class="text-xs">Rekap</span></button>
      <button onclick="switchPage('patroli')" class="py-2 flex flex-col items-center ${currentPage==='patroli'?'text-red-800':'text-gray-500'}"><img src="https://raw.githubusercontent.com/ekyarsakarya-eng/absensi-JSKN/main/icon-patroli.png" class="w-6 h-6 mb-1 ${currentPage==='patroli'?'':'opacity-50'}"><span class="text-xs">Patroli</span></button>
      <button onclick="switchPage('kejadian')" class="py-2 flex flex-col items-center ${currentPage==='kejadian'?'text-red-800':'text-gray-500'}"><img src="https://raw.githubusercontent.com/ekyarsakarya-eng/absensi-JSKN/main/icon-kejadian.png" class="w-6 h-6 mb-1 ${currentPage==='kejadian'?'':'opacity-50'}"><span class="text-xs">Kejadian</span></button>
      <button onclick="switchPage('pembinaan')" class="py-2 flex flex-col items-center ${currentPage==='pembinaan'?'text-red-800':'text-gray-500'}"><img src="https://raw.githubusercontent.com/ekyarsakarya-eng/absensi-JSKN/main/icon-pembinaan.png" class="w-6 h-6 mb-1 ${currentPage==='pembinaan'?'':'opacity-50'}"><span class="text-xs">Bina</span></button>
    </div>
  </div>

  <!-- MODAL CAMERA -->
  <div id="modalCam" class="fixed inset-0 bg-black/90 hidden items-center justify-center p-4 z-50"><div class="bg-white dark:bg-gray-800 rounded-2xl p-4 w-full max-w-md"><h3 class="font-bold text-center mb-2">Ambil Foto</h3><div class="relative"><video id="video" autoplay playsinline class="w-full rounded-lg bg-black"></video><canvas id="canvas" class="hidden"></canvas><div id="timemarkPreview" class="absolute bottom-2 left-2 bg-black/70 text-white text-xs p-2 rounded"><div id="previewHari"></div><div id="previewJam" class="text-yellow-400"></div><div id="previewNama"></div><div id="previewGps" class="text-green-400"></div></div></div><div class="flex gap-2 mt-3"><button onclick="capture()" id="btnCapture" class="flex-1 bg-red-800 text-white p-3 rounded-lg">Kirim</button><button onclick="closeCam()" class="bg-gray-500 text-white px-4 rounded-lg">Batal</button></div></div></div>

  <!-- MODAL PROFIL -->
  <div id="modalProfil" class="fixed inset-0 bg-black/70 hidden items-center justify-center p-4 z-50"><div class="bg-white dark:bg-gray-900 rounded-3xl w-full max-w-md overflow-hidden"><div class="bg-red-800 p-6 text-white text-center relative"><button onclick="closeProfil()" class="absolute top-3 right-3">✕</button><img id="fotoProfil" src="${user.foto||''}" class="w-24 h-24 rounded-2xl mx-auto border-4 border-white object-cover"><h3 class="font-bold mt-2">${user.nama}</h3><p class="text-sm opacity-80">@${user.username}</p><button onclick="gantiFotoProfil()" class="absolute bottom-4 right-4 bg-white text-red-800 w-8 h-8 rounded-full"><i class="fa-solid fa-camera text-xs"></i></button></div><div class="p-4 space-y-2"><button onclick="openEditProfil()" class="w-full p-3 bg-gray-100 dark:bg-gray-800 rounded-xl text-left">Edit Profil</button><button onclick="openGantiPassword()" class="w-full p-3 bg-gray-100 dark:bg-gray-800 rounded-xl text-left">Ganti Password</button><button onclick="logout()" class="w-full p-3 bg-red-50 text-red-600 rounded-xl text-left">Logout</button></div></div></div>
  <input type="file" id="inputFotoProfil" accept="image/*" class="hidden" onchange="uploadFotoProfil(event)">

  <!-- MODAL EDIT PROFIL -->
  <div id="modalEditProfil" class="fixed inset-0 bg-black/70 hidden items-center justify-center p-4 z-[60]"><div class="bg-white dark:bg-gray-900 rounded-3xl w-full max-w-md"><div class="bg-red-800 p-4 text-white flex justify-between"><h3 class="font-bold">Edit Profil</h3><button onclick="closeEditProfil()">✕</button></div><div class="p-4 space-y-3 max-h- overflow-y-auto"><input id="editNama" value="${user.nama||''}" placeholder="Nama" class="w-full p-2 border rounded dark:bg-gray-800"><input id="editKtp" value="${user.ktp||''}" placeholder="KTP" class="w-full p-2 border rounded dark:bg-gray-800"><input id="editHp" value="${user.hp||''}" placeholder="HP" class="w-full p-2 border rounded dark:bg-gray-800"><textarea id="editAlamat" placeholder="Alamat" class="w-full p-2 border rounded dark:bg-gray-800">${user.alamat||''}</textarea><input id="editTtl" value="${user.ttl||''}" placeholder="TTL" class="w-full p-2 border rounded dark:bg-gray-800"><input id="editBank" value="${user.bank||''}" placeholder="Bank" class="w-full p-2 border rounded dark:bg-gray-800"><input id="editRek" value="${user.rekening||''}" placeholder="Rekening" class="w-full p-2 border rounded dark:bg-gray-800"></div><div class="p-4"><button onclick="simpanProfil()" id="btnSimpanProfil" class="w-full bg-red-800 text-white p-3 rounded-xl">Simpan</button></div></div></div>

  <!-- MODAL GANTI PASSWORD -->
  <div id="modalGantiPassword" class="fixed inset-0 bg-black/70 hidden items-center justify-center p-4 z-[60]"><div class="bg-white dark:bg-gray-900 rounded-3xl w-full max-w-md"><div class="bg-red-800 p-4 text-white flex justify-between"><h3 class="font-bold">Ganti Password</h3><button onclick="closeGantiPassword()">✕</button></div><div class="p-4 space-y-3"><input id="passLama" type="password" placeholder="Password Lama" class="w-full p-2 border rounded dark:bg-gray-800"><input id="passBaru" type="password" placeholder="Password Baru" class="w-full p-2 border rounded dark:bg-gray-800"><input id="passBaru2" type="password" placeholder="Ulangi Password Baru" class="w-full p-2 border rounded dark:bg-gray-800"><button onclick="gantiPassword()" class="w-full bg-red-800 text-white p-3 rounded-xl">Simpan</button></div></div></div>

  <!-- MODAL PATROLI -->
  <div id="modalPatroli" class="fixed inset-0 bg-black/70 hidden items-center justify-center p-4 z-[60]"><div class="bg-white dark:bg-gray-900 rounded-3xl w-full max-w-md"><div class="bg-red-800 p-4 text-white flex justify-between"><h3 class="font-bold">Tambah Patroli</h3><button onclick="closeFormPatroli()">✕</button></div><div class="p-4 space-y-3"><input id="patroliLokasi" placeholder="Lokasi Patroli" class="w-full p-2 border rounded dark:bg-gray-800"><textarea id="patroliKet" placeholder="Keterangan" class="w-full p-2 border rounded dark:bg-gray-800"></textarea><input type="file" id="patroliFoto" accept="image/*" class="w-full text-sm"><button onclick="simpanPatroli()" class="w-full bg-red-800 text-white p-3 rounded-xl">Simpan</button></div></div></div>

  <!-- MODAL KEJADIAN -->
  <div id="modalKejadian" class="fixed inset-0 bg-black/70 hidden items-center justify-center p-4 z-[60]"><div class="bg-white dark:bg-gray-900 rounded-3xl w-full max-w-md"><div class="bg-red-800 p-4 text-white flex justify-between"><h3 class="font-bold">Lapor Kejadian</h3><button onclick="closeFormKejadian()">✕</button></div><div class="p-4 space-y-3"><select id="kejadianJenis" class="w-full p-2 border rounded dark:bg-gray-800"><option>Keamanan</option><option>Kebakaran</option><option>Medis</option><option>Lainnya</option></select><input id="kejadianLokasi" placeholder="Lokasi" class="w-full p-2 border rounded dark:bg-gray-800"><textarea id="kejadianKronologi" placeholder="Kronologi" class="w-full p-2 border rounded dark:bg-gray-800"></textarea><input type="file" id="kejadianFoto" accept="image/*" class="w-full text-sm"><button onclick="simpanKejadian()" class="w-full bg-red-800 text-white p-3 rounded-xl">Kirim Laporan</button></div></div></div>

  <!-- MODAL PEMBINAAN -->
  <div id="modalPembinaan" class="fixed inset-0 bg-black/70 hidden items-center justify-center p-4 z-[60]"><div class="bg-white dark:bg-gray-900 rounded-3xl w-full max-w-md"><div class="bg-red-800 p-4 text-white flex justify-between"><h3 class="font-bold">Tambah Pembinaan</h3><button onclick="closeFormPembinaan()">✕</button></div><div class="p-4 space-y-3"><input id="binaMateri" placeholder="Materi" class="w-full p-2 border rounded dark:bg-gray-800"><input id="binaPelatih" placeholder="Pelatih" class="w-full p-2 border rounded dark:bg-gray-800"><input id="binaNilai" type="number" placeholder="Nilai" class="w-full p-2 border rounded dark:bg-gray-800"><textarea id="binaKet" placeholder="Keterangan" class="w-full p-2 border rounded dark:bg-gray-800"></textarea><button onclick="simpanPembinaan()" class="w-full bg-red-800 text-white p-3 rounded-xl">Simpan</button></div></div></div>
  `;
  if(currentPage==='home'){cekStatus();dapatkanLokasiGPS();}
  if(currentPage==='rekap')loadRekap();
  if(currentPage==='patroli')loadPatroli();
  if(currentPage==='kejadian')loadKejadian();
  if(currentPage==='pembinaan')loadPembinaan();
}

function renderPage(){switch(currentPage){case'home':return renderHome();case'rekap':return renderRekap();case'patroli':return renderPatroli();case'kejadian':return renderKejadian();case'pembinaan':return renderPembinaan();}}
function renderHome(){const s=statusServer;const bisaIn=s.bisaIn;const bisaOut=s.bisaOut;return`<div class="space-y-4"><div class="bg-white dark:bg-gray-800 p-4 rounded-2xl shadow"><p class="text-xs text-gray-500">GPS</p><p id="gpsAlamat" class="text-sm">${currentLocation.alamat}</p><div class="grid grid-cols-2 text-xs mt-2"><p>Lat: <span id="gpsLat">${currentLocation.lat}</span></p><p>Long: <span id="gpsLong">${currentLocation.long}</span></p></div></div><div class="bg-white dark:bg-gray-800 p-4 rounded-2xl shadow"><div class="flex justify-between"><h2 class="font-bold">Status</h2><span class="text-xs">${s.bisaIn?'Siap Masuk':s.bisaOut?'Siap Pulang':'Selesai'}</span></div><div class="grid grid-cols-2 gap-2 mt-2"><div class="bg-green-50 p-2 rounded text-center"><p class="text-xs">Masuk</p><p class="font-bold">${s.jamMasuk||'--:--'}</p></div><div class="bg-red-50 p-2 rounded text-center"><p class="text-xs">Pulang</p><p class="font-bold">${s.jamPulang||'--:--'}</p></div></div><p class="text-center mt-2 font-mono" id="jamRealtime">--:--:--</p></div><button onclick="bukaKameraAbsen('Masuk')" ${!bisaIn?'disabled':''} class="w-full ${bisaIn?'bg-green-600':'bg-gray-300'} text-white p-4 rounded-2xl">Absen Masuk</button><button onclick="bukaKameraAbsen('Pulang')" ${!bisaOut?'disabled':''} class="w-full ${bisaOut?'bg-red-800':'bg-gray-300'} text-white p-4 rounded-2xl">Absen Pulang</button></div>`;}
function renderRekap(){return`<div class="bg-white dark:bg-gray-800 p-4 rounded-2xl"><h2 class="font-bold mb-2">Rekap Absensi</h2><div id="listRekap">Loading...</div></div>`;}
function renderPatroli(){return`<div class="bg-white dark:bg-gray-800 p-4 rounded-2xl"><div class="flex justify-between mb-2"><h2 class="font-bold">Patroli</h2><button onclick="openFormPatroli()" class="bg-red-800 text-white px-3 py-1 rounded text-sm">+ Tambah</button></div><div id="listPatroli">Loading...</div></div>`;}
function renderKejadian(){return`<div class="bg-white dark:bg-gray-800 p-4 rounded-2xl"><div class="flex justify-between mb-2"><h2 class="font-bold">Kejadian</h2><button onclick="openFormKejadian()" class="bg-red-800 text-white px-3 py-1 rounded text-sm">+ Lapor</button></div><div id="listKejadian">Loading...</div></div>`;}
function renderPembinaan(){return`<div class="bg-white dark:bg-gray-800 p-4 rounded-2xl"><div class="flex justify-between mb-2"><h2 class="font-bold">Pembinaan</h2><button onclick="openFormPembinaan()" class="bg-red-800 text-white px-3 py-1 rounded text-sm">+ Tambah</button></div><div id="listPembinaan">Loading...</div></div>`;}
// === FUNGSI INTI ===
function updateJamRealtime(){const e=document.getElementById('jamRealtime');if(e)e.textContent=new Date().toLocaleTimeString('id-ID',{hour12:false});}
setInterval(updateJamRealtime,1000);

async function loadRekap(){const r=await api('getRekap',{username:user.username});const e=document.getElementById('listRekap');if(!e)return;if(r.status!=='success'||!r.data.length){e.innerHTML='<p class="text-center text-gray-500 py-4">Belum ada data</p>';return;}dataRekap=r.data;e.innerHTML=dataRekap.map(d=>{const t=new Date(d.tanggal);return`<div class="flex justify-between items-center p-3 border-b dark:border-gray-700"><div><p class="font-medium">${t.toLocaleDateString('id-ID',{day:'2-digit',month:'short'})}</p><p class="text-xs text-gray-500">${d.jamMasuk||'-'} - ${d.jamPulang||'-'}</p></div><span class="text-xs px-2 py-1 rounded-full ${d.status==='Hadir'?'bg-green-100 text-green-800':'bg-gray-100'}">${d.keterangan||d.status}</span></div>`;}).join('');}

async function loadPatroli(){const r=await api('getPatroli',{username:user.username});const e=document.getElementById('listPatroli');if(!e)return;if(r.status!=='success'||!r.data.length){e.innerHTML='<p class="text-center text-gray-500 py-4">Belum ada patroli</p>';return;}dataPatroli=r.data;e.innerHTML=dataPatroli.map(p=>{const t=new Date(p.timestamp).toLocaleString('id-ID',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});return`<div class="p-3 mb-2 bg-gray-50 dark:bg-gray-700/50 rounded-xl border"><div class="flex justify-between items-start"><div><p class="font-bold text-red-800 dark:text-white text-sm">${p.nama||p.username}</p><p class="text-xs text-gray-500">${t}</p></div>${p.foto?`<img src="${p.foto}" class="w-12 h-12 rounded object-cover">`:''}</div><p class="text-sm mt-2"><i class="fa-solid fa-location-dot text-red-600 mr-1"></i>${p.lokasi}</p><p class="text-xs text-gray-600 dark:text-gray-300">${p.keterangan}</p></div>`;}).join('');}

async function loadKejadian(){const r=await api('getKejadian',{username:user.username});const e=document.getElementById('listKejadian');if(!e)return;if(r.status!=='success'||!r.data.length){e.innerHTML='<p class="text-center text-gray-500 py-4">Belum ada laporan</p>';return;}dataKejadian=r.data;e.innerHTML=dataKejadian.map(k=>{const t=new Date(k.timestamp).toLocaleString('id-ID',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'});return`<div class="p-3 mb-2 bg-gray-50 dark:bg-gray-700/50 rounded-xl border"><div class="flex justify-between"><p class="font-bold text-red-800 dark:text-white text-sm">${k.nama||k.username}</p><span class="text-xs px-2 py-0.5 bg-amber-100 text-amber-800 rounded-full">${k.jenis}</span></div><p class="text-xs text-gray-500">${t} • ${k.lokasi}</p><p class="text-sm mt-1">${k.kronologi}</p>${k.foto?`<img src="${k.foto}" class="mt-2 rounded w-full max-h-40 object-cover">`:''}</div>`;}).join('');}

async function loadPembinaan(){const r=await api('getPembinaan',{username:user.username});const e=document.getElementById('listPembinaan');if(!e)return;if(r.status!=='success'||!r.data.length){e.innerHTML='<p class="text-center text-gray-500 py-4">Belum ada data</p>';return;}dataPembinaan=r.data;e.innerHTML=dataPembinaan.map(b=>{const t=new Date(b.timestamp).toLocaleDateString('id-ID');return`<div class="p-3 mb-2 bg-gray-50 dark:bg-gray-700/50 rounded-xl border"><div class="flex justify-between"><p class="font-bold text-red-800 dark:text-white text-sm">${b.nama||b.username}</p><p class="text-xs text-gray-500">${t}</p></div><p class="text-sm mt-1">Materi: ${b.materi}</p><p class="text-xs">Pelatih: ${b.pelatih} • Nilai: <b>${b.nilai}</b></p><p class="text-xs text-gray-600">${b.keterangan||''}</p></div>`;}).join('');}

function switchPage(p){currentPage=p;renderDashboard();}
function dapatkanLokasiGPS(){if(!navigator.geolocation)return;navigator.geolocation.watchPosition(pos=>{currentLocation.lat=pos.coords.latitude.toFixed(6);currentLocation.long=pos.coords.longitude.toFixed(6);document.getElementById('gpsLat')&&(document.getElementById('gpsLat').textContent=currentLocation.lat);document.getElementById('gpsLong')&&(document.getElementById('gpsLong').textContent=currentLocation.long);fetch(`https://nominatim.openstreetmap.org/reverse?format=json&lat=${currentLocation.lat}&lon=${currentLocation.long}`).then(r=>r.json()).then(d=>{if(d.display_name){currentLocation.alamat=d.display_name;document.getElementById('gpsAlamat')&&(document.getElementById('gpsAlamat').textContent=d.display_name);}}).catch(()=>{});},{enableHighAccuracy:true,maximumAge:0});}
function bukaKameraAbsen(t){currentType=t;openCam();}
function openCam(){const m=document.getElementById('modalCam');m.classList.remove('hidden');m.classList.add('flex');startTimemark();navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}}}).then(s=>{stream=s;document.getElementById('video').srcObject=s;}).catch(e=>{showError('Kamera error: '+e.message);closeCam();});}
function closeCam(){const m=document.getElementById('modalCam');m.classList.add('hidden');m.classList.remove('flex');if(stream){stream.getTracks().forEach(t=>t.stop());stream=null;}if(animationFrame)cancelAnimationFrame(animationFrame);}
function startTimemark(){function u(){const n=new Date();document.getElementById('previewHari')&&(document.getElementById('previewHari').textContent=n.toLocaleDateString('id-ID',{weekday:'long',day:'2-digit',month:'long'}));document.getElementById('previewJam')&&(document.getElementById('previewJam').textContent=n.toLocaleTimeString('id-ID'));document.getElementById('previewNama')&&(document.getElementById('previewNama').textContent=user.nama);document.getElementById('previewGps')&&(document.getElementById('previewGps').textContent=`${currentLocation.lat}, ${currentLocation.long}`);animationFrame=requestAnimationFrame(u);}u();}
async function capture(){const v=document.getElementById('video');const c=document.getElementById('canvas');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);const foto=c.toDataURL('image/jpeg',0.8);closeCam();const btn=document.getElementById('btnCapture');btn&&(btn.disabled=true);const r=await api('absen',{username:user.username,tipeAbsen:currentType,foto,lat:currentLocation.lat,long:currentLocation.long,alamat:currentLocation.alamat});btn&&(btn.disabled=false);if(r.status==='success'){showSuccess(r.message);cekStatus();}else{showError(r.message);}}
async function api(a,p={}){try{const r=await fetch(URL_GAS,{method:'POST',mode:'cors',headers:{'Content-Type':'text/plain'},body:JSON.stringify({aksi:a,data:p})});return await r.json();}catch(e){return{status:'error',message:e.message};}}
function openProfil(){document.getElementById('modalProfil').classList.remove('hidden');document.getElementById('modalProfil').classList.add('flex');}
function closeProfil(){document.getElementById('modalProfil').classList.add('hidden');}
function gantiFotoProfil(){document.getElementById('inputFotoProfil').click();}
async function uploadFotoProfil(e){const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=async ev=>{const b=ev.target.result;const res=await api('uploadFoto',{username:user.username,fotoBase64:b});if(res.status==='success'){user.foto=res.urlFoto;localStorage.setItem('user',JSON.stringify(user));document.getElementById('avatarNav').src=res.urlFoto;document.getElementById('fotoProfil').src=res.urlFoto;showSuccess('Foto profil diperbarui');}else{showError(res.message);}};r.readAsDataURL(f);}
function openEditProfil(){closeProfil();document.getElementById('modalEditProfil').classList.remove('hidden');document.getElementById('modalEditProfil').classList.add('flex');}
function closeEditProfil(){document.getElementById('modalEditProfil').classList.add('hidden');}
async function simpanProfil(){const d={username:user.username,nama:document.getElementById('editNama').value,ktp:document.getElementById('editKtp').value,hp:document.getElementById('editHp').value,alamat:document.getElementById('editAlamat').value,ttl:document.getElementById('editTtl').value,bank:document.getElementById('editBank').value,rekening:document.getElementById('editRek').value};const b=document.getElementById('btnSimpanProfil');b.disabled=true;const r=await api('updateProfil',d);b.disabled=false;if(r.status==='success'){showSuccess(r.message);Object.assign(user,d);localStorage.setItem('user',JSON.stringify(user));closeEditProfil();renderDashboard();}else{showError(r.message);}}
function openGantiPassword(){closeProfil();document.getElementById('modalGantiPassword').classList.remove('hidden');document.getElementById('modalGantiPassword').classList.add('flex');}
function closeGantiPassword(){document.getElementById('modalGantiPassword').classList.add('hidden');}
async function gantiPassword(){const l=document.getElementById('passLama').value;const b=document.getElementById('passBaru').value;const b2=document.getElementById('passBaru2').value;if(!l||!b)return showError('Lengkapi semua');if(b!==b2)return showError('Password baru tidak cocok');const r=await api('gantiPassword',{username:user.username,passwordLama:l,passwordBaru:b});if(r.status==='success'){showSuccess(r.message);closeGantiPassword();}else{showError(r.message);}}
function openFormPatroli(){document.getElementById('modalPatroli').classList.remove('hidden');document.getElementById('modalPatroli').classList.add('flex');}
function closeFormPatroli(){document.getElementById('modalPatroli').classList.add('hidden');}
async function simpanPatroli(){const lokasi=document.getElementById('patroliLokasi').value;const ket=document.getElementById('patroliKet').value;const f=document.getElementById('patroliFoto').files[0];if(!lokasi)return showError('Isi lokasi');let foto='';if(f){foto=await toBase64(f);}const r=await api('tambahPatroli',{username:user.username,nama:user.nama,lokasi,keterangan:ket,foto,lat:currentLocation.lat,long:currentLocation.long});if(r.status==='success'){showSuccess('Patroli disimpan');closeFormPatroli();loadPatroli();}else{showError(r.message);}}
function openFormKejadian(){document.getElementById('modalKejadian').classList.remove('hidden');document.getElementById('modalKejadian').classList.add('flex');}
function closeFormKejadian(){document.getElementById('modalKejadian').classList.add('hidden');}
async function simpanKejadian(){const jenis=document.getElementById('kejadianJenis').value;const lokasi=document.getElementById('kejadianLokasi').value;const kronologi=document.getElementById('kejadianKronologi').value;const f=document.getElementById('kejadianFoto').files[0];if(!lokasi||!kronologi)return showError('Lengkapi data');let foto='';if(f){foto=await toBase64(f);}const r=await api('tambahKejadian',{username:user.username,nama:user.nama,jenis,lokasi,kronologi,foto});if(r.status==='success'){showSuccess('Laporan terkirim');closeFormKejadian();loadKejadian();}else{showError(r.message);}}
function openFormPembinaan(){document.getElementById('modalPembinaan').classList.remove('hidden');document.getElementById('modalPembinaan').classList.add('flex');}
function closeFormPembinaan(){document.getElementById('modalPembinaan').classList.add('hidden');}
async function simpanPembinaan(){const materi=document.getElementById('binaMateri').value;const pelatih=document.getElementById('binaPelatih').value;const nilai=document.getElementById('binaNilai').value;const ket=document.getElementById('binaKet').value;if(!materi)return showError('Isi materi');const r=await api('tambahPembinaan',{username:user.username,nama:user.nama,materi,pelatih,nilai,keterangan:ket});if(r.status==='success'){showSuccess('Data disimpan');closeFormPembinaan();loadPembinaan();}else{showError(r.message);}}
function toBase64(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file);});}
async function cekStatus(){const r=await api('cekStatus',{username:user.username});if(r.status==='success'){statusServer=r;if(currentPage==='home'){document.getElementById('contentArea').innerHTML=renderPage();updateJamRealtime();}}}
console.log('App started');render();
